### ISSUE TITLE
Add spell-check-md-files unit tests

### ISSUE THREAD

**Issue by CompSciLauren** [CompSciLauren/awesome-git-hooks#16]
**Is your feature request related to a problem? Please describe.**
The spell-check-md-files script doesn't have any tests yet.

**Describe the solution you'd like**
Add one or more unit tests. [Here is an example.](https://github.com/CompSciLauren/awesome-git-hooks/blob/master/tests/verify-name-and-email-test.bats)

This project uses the [BATS](https://github.com/jasonkarns/bats-mock) testing framework.

**Comment by Anarcroth** [comment]
This looks pretty cool! :) I'd love to do some tests for the spell-check. Mind if I take this?

**Comment by CompSciLauren** [comment]
Please do! 😄

**Comment by CompSciLauren** [comment]
No preferences! You can just do whatever comes to mind. But if you end up with any questions, need help, or just want more specific requirements, let me know and I'll do my best to help out. Thanks for taking up this issue! :)
