### ISSUE TITLE
verify-name-and-email test pollutes local git config

### ISSUE THREAD

**Issue by zackse** [CompSciLauren/awesome-git-hooks#31]
**Description of Bug**
After running the verify-name-and-email unit tests, the local git config is unconditionally updated with a hardcoded `user.name` and `user.email`.

**Steps to Reproduce**
1. Run `bats tests/verify-name-and-email-test.bats`
2. Run `git config --local user.name; git config --local user.email`
3. Observe name/email in output

**Expected behavior**
Any existing local config for `user.name` and `user.email` should be preserved. If there isn't a local configuration for those fields, they should remain unset.

```
$ git config --local --remove-section user

# note: no output (fields are unset)
$ git config --local user.name
$ git config --local user.email

$ bats tests/verify-name-and-email-test.bats
 ✓ incorrect name throws error
 ✓ incorrect email throws error

2 tests, 0 failures

# note new values
$ git config --local user.name
Lauren Stephenson
$ git config --local user.email
compscilauren@gmail.com
```

**Comment by CompSciLauren** [comment]
Resolved thanks to PR #32, closing.
